Add support for StatusMask | StatusMask
Even though StatusMask inherits from std::bitset, if you attempt to do
StatusMask|StatusMask it complains because the resulting type is
a bitset, not a StatusMask. Also the expected operator supported for
a StatusMask should be OR not bitshift that accumulates.

    error: could not convert
    ‘std::operator|<32>(std::operator|<32>(std::operator|<32>(
    std::operator|<32>(dds::core::status::StatusMask::none(),
    dds::core::status::StatusMask::offered_deadline_missed()),
    dds::core::status::StatusMask::offered_incompatible_qos()),
    dds::core::status::StatusMask::liveliness_lost()),
    dds::core::status::StatusMask::publication_matched())’ from
    ‘std::bitset<32>’ to ‘dds::core::status::StatusMask’